"""brand-design — generated by harness_emit.py from .claude-plugin/plugin.json. Do not edit."""
import os

_HERE = os.path.dirname(os.path.abspath(__file__))

def register(ctx):
    ctx.register_skill('brand-advertising-facts', os.path.join(_HERE, "skills", 'brand-advertising-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('brand-corpus', os.path.join(_HERE, "skills", 'brand-corpus', "SKILL.md"))  # one per skill
    ctx.register_skill('brand-guidelines', os.path.join(_HERE, "skills", 'brand-guidelines', "SKILL.md"))  # one per skill
    ctx.register_skill('brand-identity-facts', os.path.join(_HERE, "skills", 'brand-identity-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('brand-methodology-rules', os.path.join(_HERE, "skills", 'brand-methodology-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('brand-rubrics', os.path.join(_HERE, "skills", 'brand-rubrics', "SKILL.md"))  # one per skill
    ctx.register_skill('brand-strategy-facts', os.path.join(_HERE, "skills", 'brand-strategy-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('brand-voice-facts', os.path.join(_HERE, "skills", 'brand-voice-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('check-brand-council', os.path.join(_HERE, "skills", 'check-brand-council', "SKILL.md"))  # one per skill
    ctx.register_skill('check-brand-orientation', os.path.join(_HERE, "skills", 'check-brand-orientation', "SKILL.md"))  # one per skill
    ctx.register_skill('check-brand-rubric', os.path.join(_HERE, "skills", 'check-brand-rubric', "SKILL.md"))  # one per skill
    ctx.register_skill('council-rules', os.path.join(_HERE, "skills", 'council-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('file-brand', os.path.join(_HERE, "skills", 'file-brand', "SKILL.md"))  # one per skill
    ctx.register_skill('file-brand-corpus', os.path.join(_HERE, "skills", 'file-brand-corpus', "SKILL.md"))  # one per skill
    ctx.register_skill('make-brand', os.path.join(_HERE, "skills", 'make-brand', "SKILL.md"))  # one per skill
    ctx.register_skill('make-brand-guidelines', os.path.join(_HERE, "skills", 'make-brand-guidelines', "SKILL.md"))  # one per skill
    ctx.register_skill('make-brand-muse', os.path.join(_HERE, "skills", 'make-brand-muse', "SKILL.md"))  # one per skill
    ctx.register_skill('make-brand-stack', os.path.join(_HERE, "skills", 'make-brand-stack', "SKILL.md"))  # one per skill
    ctx.register_skill('make-council', os.path.join(_HERE, "skills", 'make-council', "SKILL.md"))  # one per skill
    ctx.register_skill('make-critic', os.path.join(_HERE, "skills", 'make-critic', "SKILL.md"))  # one per skill
