"""frontend — generated by harness_emit.py from .claude-plugin/plugin.json. Do not edit."""
import os

_HERE = os.path.dirname(os.path.abspath(__file__))

def register(ctx):
    ctx.register_skill('apple-mobile-facts', os.path.join(_HERE, "skills", 'apple-mobile-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('break-down-flow', os.path.join(_HERE, "skills", 'break-down-flow', "SKILL.md"))  # one per skill
    ctx.register_skill('break-down-layout', os.path.join(_HERE, "skills", 'break-down-layout', "SKILL.md"))  # one per skill
    ctx.register_skill('check-focus', os.path.join(_HERE, "skills", 'check-focus', "SKILL.md"))  # one per skill
    ctx.register_skill('check-safety', os.path.join(_HERE, "skills", 'check-safety', "SKILL.md"))  # one per skill
    ctx.register_skill('check-speed', os.path.join(_HERE, "skills", 'check-speed', "SKILL.md"))  # one per skill
    ctx.register_skill('check-translations', os.path.join(_HERE, "skills", 'check-translations', "SKILL.md"))  # one per skill
    ctx.register_skill('check-ui-change', os.path.join(_HERE, "skills", 'check-ui-change', "SKILL.md"))  # one per skill
    ctx.register_skill('check-whole-ui', os.path.join(_HERE, "skills", 'check-whole-ui', "SKILL.md"))  # one per skill
    ctx.register_skill('css-system-facts', os.path.join(_HERE, "skills", 'css-system-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('data-wiring-facts', os.path.join(_HERE, "skills", 'data-wiring-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('dom-layout-facts', os.path.join(_HERE, "skills", 'dom-layout-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('feature-intake-rules', os.path.join(_HERE, "skills", 'feature-intake-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('make-component', os.path.join(_HERE, "skills", 'make-component', "SKILL.md"))  # one per skill
    ctx.register_skill('motion-rules', os.path.join(_HERE, "skills", 'motion-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('persistence-facts', os.path.join(_HERE, "skills", 'persistence-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('reactivity-facts', os.path.join(_HERE, "skills", 'reactivity-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('size-and-shape-rules', os.path.join(_HERE, "skills", 'size-and-shape-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('state-model-rules', os.path.join(_HERE, "skills", 'state-model-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('ui-genre-facts', os.path.join(_HERE, "skills", 'ui-genre-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('ui-pattern-facts', os.path.join(_HERE, "skills", 'ui-pattern-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('web-component-facts', os.path.join(_HERE, "skills", 'web-component-facts', "SKILL.md"))  # one per skill
