"""llm — generated by harness_emit.py from .claude-plugin/plugin.json. Do not edit."""
import os

_HERE = os.path.dirname(os.path.abspath(__file__))

def register(ctx):
    ctx.register_skill('agent-residency-facts', os.path.join(_HERE, "skills", 'agent-residency-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('chat-harness-guardrail-facts', os.path.join(_HERE, "skills", 'chat-harness-guardrail-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('chat-harness-logging-facts', os.path.join(_HERE, "skills", 'chat-harness-logging-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('chat-harness-memory-facts', os.path.join(_HERE, "skills", 'chat-harness-memory-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('chat-harness-routing-facts', os.path.join(_HERE, "skills", 'chat-harness-routing-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('chat-harness-runtime-resilience-facts', os.path.join(_HERE, "skills", 'chat-harness-runtime-resilience-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('chat-harness-tool-facts', os.path.join(_HERE, "skills", 'chat-harness-tool-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('chat-harness-workflow-facts', os.path.join(_HERE, "skills", 'chat-harness-workflow-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('llm-gateway-facts', os.path.join(_HERE, "skills", 'llm-gateway-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('llm-streaming-facts', os.path.join(_HERE, "skills", 'llm-streaming-facts', "SKILL.md"))  # one per skill
