"""harness — generated by harness_emit.py from .claude-plugin/plugin.json. Do not edit."""
import os

_HERE = os.path.dirname(os.path.abspath(__file__))

def register(ctx):
    ctx.register_skill('adopt-plugin', os.path.join(_HERE, "skills", 'adopt-plugin', "SKILL.md"))  # one per skill
    ctx.register_skill('agent-writing-rules', os.path.join(_HERE, "skills", 'agent-writing-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('big-change-git-rules', os.path.join(_HERE, "skills", 'big-change-git-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('blocked-by-rules', os.path.join(_HERE, "skills", 'blocked-by-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('break-down-problem', os.path.join(_HERE, "skills", 'break-down-problem', "SKILL.md"))  # one per skill
    ctx.register_skill('check-all-agents', os.path.join(_HERE, "skills", 'check-all-agents', "SKILL.md"))  # one per skill
    ctx.register_skill('check-all-skills', os.path.join(_HERE, "skills", 'check-all-skills', "SKILL.md"))  # one per skill
    ctx.register_skill('check-entry-file', os.path.join(_HERE, "skills", 'check-entry-file', "SKILL.md"))  # one per skill
    ctx.register_skill('check-everything', os.path.join(_HERE, "skills", 'check-everything', "SKILL.md"))  # one per skill
    ctx.register_skill('check-reconstructibility', os.path.join(_HERE, "skills", 'check-reconstructibility', "SKILL.md"))  # one per skill
    ctx.register_skill('check-routing', os.path.join(_HERE, "skills", 'check-routing', "SKILL.md"))  # one per skill
    ctx.register_skill('check-skill', os.path.join(_HERE, "skills", 'check-skill', "SKILL.md"))  # one per skill
    ctx.register_skill('check-state', os.path.join(_HERE, "skills", 'check-state', "SKILL.md"))  # one per skill
    ctx.register_skill('checking-rules', os.path.join(_HERE, "skills", 'checking-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('clean-git', os.path.join(_HERE, "skills", 'clean-git', "SKILL.md"))  # one per skill
    ctx.register_skill('clean-repo', os.path.join(_HERE, "skills", 'clean-repo', "SKILL.md"))  # one per skill
    ctx.register_skill('entry-file-rules', os.path.join(_HERE, "skills", 'entry-file-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('estate-maintenance', os.path.join(_HERE, "skills", 'estate-maintenance', "SKILL.md"))  # one per skill
    ctx.register_skill('find-intent', os.path.join(_HERE, "skills", 'find-intent', "SKILL.md"))  # one per skill
    ctx.register_skill('find-open-questions', os.path.join(_HERE, "skills", 'find-open-questions', "SKILL.md"))  # one per skill
    ctx.register_skill('github-facts', os.path.join(_HERE, "skills", 'github-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('hook-writing-rules', os.path.join(_HERE, "skills", 'hook-writing-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('make-agent', os.path.join(_HERE, "skills", 'make-agent', "SKILL.md"))  # one per skill
    ctx.register_skill('make-hook', os.path.join(_HERE, "skills", 'make-hook', "SKILL.md"))  # one per skill
    ctx.register_skill('make-pack', os.path.join(_HERE, "skills", 'make-pack', "SKILL.md"))  # one per skill
    ctx.register_skill('make-plugin', os.path.join(_HERE, "skills", 'make-plugin', "SKILL.md"))  # one per skill
    ctx.register_skill('make-script', os.path.join(_HERE, "skills", 'make-script', "SKILL.md"))  # one per skill
    ctx.register_skill('make-skill', os.path.join(_HERE, "skills", 'make-skill', "SKILL.md"))  # one per skill
    ctx.register_skill('naming-rules', os.path.join(_HERE, "skills", 'naming-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('ops-write-sandbox-rules', os.path.join(_HERE, "skills", 'ops-write-sandbox-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('pack-writing-rules', os.path.join(_HERE, "skills", 'pack-writing-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('pattern-sweeping', os.path.join(_HERE, "skills", 'pattern-sweeping', "SKILL.md"))  # one per skill
    ctx.register_skill('plan-chores', os.path.join(_HERE, "skills", 'plan-chores', "SKILL.md"))  # one per skill
    ctx.register_skill('plan-plugin-split', os.path.join(_HERE, "skills", 'plan-plugin-split', "SKILL.md"))  # one per skill
    ctx.register_skill('plan-skill-merge', os.path.join(_HERE, "skills", 'plan-skill-merge', "SKILL.md"))  # one per skill
    ctx.register_skill('plan-skill-split', os.path.join(_HERE, "skills", 'plan-skill-split', "SKILL.md"))  # one per skill
    ctx.register_skill('plugin-install-facts', os.path.join(_HERE, "skills", 'plugin-install-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('plugin-writing-rules', os.path.join(_HERE, "skills", 'plugin-writing-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('prompt-wording-rules', os.path.join(_HERE, "skills", 'prompt-wording-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('repo-sync', os.path.join(_HERE, "skills", 'repo-sync', "SKILL.md"))  # one per skill
    ctx.register_skill('reshape-skill', os.path.join(_HERE, "skills", 'reshape-skill', "SKILL.md"))  # one per skill
    ctx.register_skill('runtime-state', os.path.join(_HERE, "skills", 'runtime-state', "SKILL.md"))  # one per skill
    ctx.register_skill('save-lessons', os.path.join(_HERE, "skills", 'save-lessons', "SKILL.md"))  # one per skill
    ctx.register_skill('script-writing-rules', os.path.join(_HERE, "skills", 'script-writing-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('ship-plugin', os.path.join(_HERE, "skills", 'ship-plugin', "SKILL.md"))  # one per skill
    ctx.register_skill('skill-writing-rules', os.path.join(_HERE, "skills", 'skill-writing-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('sort-issues', os.path.join(_HERE, "skills", 'sort-issues', "SKILL.md"))  # one per skill
    ctx.register_skill('sweep-chores', os.path.join(_HERE, "skills", 'sweep-chores', "SKILL.md"))  # one per skill
    ctx.register_skill('thinking-depth-rules', os.path.join(_HERE, "skills", 'thinking-depth-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('watch-adrs', os.path.join(_HERE, "skills", 'watch-adrs', "SKILL.md"))  # one per skill
    ctx.register_skill('watch-tickets', os.path.join(_HERE, "skills", 'watch-tickets', "SKILL.md"))  # one per skill
    ctx.register_skill('what-shipped', os.path.join(_HERE, "skills", 'what-shipped', "SKILL.md"))  # one per skill
    ctx.register_skill('write-handoff', os.path.join(_HERE, "skills", 'write-handoff', "SKILL.md"))  # one per skill
