"""teamwork — generated by harness_emit.py from .claude-plugin/plugin.json. Do not edit."""
import os

_HERE = os.path.dirname(os.path.abspath(__file__))

def register(ctx):
    ctx.register_skill('bind-build', os.path.join(_HERE, "skills", 'bind-build', "SKILL.md"))  # one per skill
    ctx.register_skill('bind-planning', os.path.join(_HERE, "skills", 'bind-planning', "SKILL.md"))  # one per skill
    ctx.register_skill('bind-product', os.path.join(_HERE, "skills", 'bind-product', "SKILL.md"))  # one per skill
    ctx.register_skill('bind-review', os.path.join(_HERE, "skills", 'bind-review', "SKILL.md"))  # one per skill
    ctx.register_skill('bind-team', os.path.join(_HERE, "skills", 'bind-team', "SKILL.md"))  # one per skill
    ctx.register_skill('build-feature', os.path.join(_HERE, "skills", 'build-feature', "SKILL.md"))  # one per skill
    ctx.register_skill('chores-run', os.path.join(_HERE, "skills", 'chores-run', "SKILL.md"))  # one per skill
    ctx.register_skill('close-session', os.path.join(_HERE, "skills", 'close-session', "SKILL.md"))  # one per skill
    ctx.register_skill('dispatch-ticket', os.path.join(_HERE, "skills", 'dispatch-ticket', "SKILL.md"))  # one per skill
    ctx.register_skill('fleet-bootstrap', os.path.join(_HERE, "skills", 'fleet-bootstrap', "SKILL.md"))  # one per skill
    ctx.register_skill('fleet-rules', os.path.join(_HERE, "skills", 'fleet-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('fork-agent', os.path.join(_HERE, "skills", 'fork-agent', "SKILL.md"))  # one per skill
    ctx.register_skill('grill-the-ask', os.path.join(_HERE, "skills", 'grill-the-ask', "SKILL.md"))  # one per skill
    ctx.register_skill('init-repo', os.path.join(_HERE, "skills", 'init-repo', "SKILL.md"))  # one per skill
    ctx.register_skill('loop-rules', os.path.join(_HERE, "skills", 'loop-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('mobilize-chores', os.path.join(_HERE, "skills", 'mobilize-chores', "SKILL.md"))  # one per skill
    ctx.register_skill('parallel-work-rules', os.path.join(_HERE, "skills", 'parallel-work-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('sub-agent', os.path.join(_HERE, "skills", 'sub-agent', "SKILL.md"))  # one per skill
    ctx.register_skill('team-scaffolding', os.path.join(_HERE, "skills", 'team-scaffolding', "SKILL.md"))  # one per skill
