"""design — generated by harness_emit.py from .claude-plugin/plugin.json. Do not edit."""
import os

_HERE = os.path.dirname(os.path.abspath(__file__))

def register(ctx):
    ctx.register_skill('artifact-styling-rules', os.path.join(_HERE, "skills", 'artifact-styling-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('check-colors', os.path.join(_HERE, "skills", 'check-colors', "SKILL.md"))  # one per skill
    ctx.register_skill('color-contrast-facts', os.path.join(_HERE, "skills", 'color-contrast-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('color-perception-facts', os.path.join(_HERE, "skills", 'color-perception-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('color-space-facts', os.path.join(_HERE, "skills", 'color-space-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('color-theory-facts', os.path.join(_HERE, "skills", 'color-theory-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('design-md-rules', os.path.join(_HERE, "skills", 'design-md-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('figma-plugin-facts', os.path.join(_HERE, "skills", 'figma-plugin-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('font-token-rules', os.path.join(_HERE, "skills", 'font-token-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('icon-rules', os.path.join(_HERE, "skills", 'icon-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('lettering-facts', os.path.join(_HERE, "skills", 'lettering-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('make-design-system', os.path.join(_HERE, "skills", 'make-design-system', "SKILL.md"))  # one per skill
    ctx.register_skill('make-dscard-kit', os.path.join(_HERE, "skills", 'make-dscard-kit', "SKILL.md"))  # one per skill
    ctx.register_skill('make-figma-make-kit', os.path.join(_HERE, "skills", 'make-figma-make-kit', "SKILL.md"))  # one per skill
    ctx.register_skill('make-palette', os.path.join(_HERE, "skills", 'make-palette', "SKILL.md"))  # one per skill
    ctx.register_skill('make-stitch-kit', os.path.join(_HERE, "skills", 'make-stitch-kit', "SKILL.md"))  # one per skill
    ctx.register_skill('make-variants', os.path.join(_HERE, "skills", 'make-variants', "SKILL.md"))  # one per skill
    ctx.register_skill('material-color-facts', os.path.join(_HERE, "skills", 'material-color-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('material-motion-facts', os.path.join(_HERE, "skills", 'material-motion-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('material-shape-facts', os.path.join(_HERE, "skills", 'material-shape-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('material-token-facts', os.path.join(_HERE, "skills", 'material-token-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('material-type-facts', os.path.join(_HERE, "skills", 'material-type-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('physical-color-facts', os.path.join(_HERE, "skills", 'physical-color-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('pick-fonts', os.path.join(_HERE, "skills", 'pick-fonts', "SKILL.md"))  # one per skill
    ctx.register_skill('token-feature-intake-rules', os.path.join(_HERE, "skills", 'token-feature-intake-rules', "SKILL.md"))  # one per skill
