"""agent-protocols — generated by harness_emit.py from .claude-plugin/plugin.json. Do not edit."""
import os

_HERE = os.path.dirname(os.path.abspath(__file__))

def register(ctx):
    ctx.register_skill('a2a-protocol-facts', os.path.join(_HERE, "skills", 'a2a-protocol-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('a2a-training-facts', os.path.join(_HERE, "skills", 'a2a-training-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('a2ui-catalog-facts', os.path.join(_HERE, "skills", 'a2ui-catalog-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('a2ui-chat-agent-facts', os.path.join(_HERE, "skills", 'a2ui-chat-agent-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('a2ui-protocol-facts', os.path.join(_HERE, "skills", 'a2ui-protocol-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('a2ui-training-facts', os.path.join(_HERE, "skills", 'a2ui-training-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('check-a2a-isolation', os.path.join(_HERE, "skills", 'check-a2a-isolation', "SKILL.md"))  # one per skill
    ctx.register_skill('make-a2a-agent', os.path.join(_HERE, "skills", 'make-a2a-agent', "SKILL.md"))  # one per skill
