"""docs — generated by harness_emit.py from .claude-plugin/plugin.json. Do not edit."""
import os

_HERE = os.path.dirname(os.path.abspath(__file__))

def register(ctx):
    ctx.register_skill('agent-harness-rules', os.path.join(_HERE, "skills", 'agent-harness-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('artifact-rules', os.path.join(_HERE, "skills", 'artifact-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('bind-intake', os.path.join(_HERE, "skills", 'bind-intake', "SKILL.md"))  # one per skill
    ctx.register_skill('check-doc', os.path.join(_HERE, "skills", 'check-doc', "SKILL.md"))  # one per skill
    ctx.register_skill('check-stage', os.path.join(_HERE, "skills", 'check-stage', "SKILL.md"))  # one per skill
    ctx.register_skill('doc-writing-rules', os.path.join(_HERE, "skills", 'doc-writing-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('file-bug', os.path.join(_HERE, "skills", 'file-bug', "SKILL.md"))  # one per skill
    ctx.register_skill('file-feature', os.path.join(_HERE, "skills", 'file-feature', "SKILL.md"))  # one per skill
    ctx.register_skill('file-leftovers', os.path.join(_HERE, "skills", 'file-leftovers', "SKILL.md"))  # one per skill
    ctx.register_skill('file-task', os.path.join(_HERE, "skills", 'file-task', "SKILL.md"))  # one per skill
    ctx.register_skill('harness-facts', os.path.join(_HERE, "skills", 'harness-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('html-to-markdown', os.path.join(_HERE, "skills", 'html-to-markdown', "SKILL.md"))  # one per skill
    ctx.register_skill('make-artifact', os.path.join(_HERE, "skills", 'make-artifact', "SKILL.md"))  # one per skill
    ctx.register_skill('make-doc', os.path.join(_HERE, "skills", 'make-doc', "SKILL.md"))  # one per skill
    ctx.register_skill('make-llms-txt', os.path.join(_HERE, "skills", 'make-llms-txt', "SKILL.md"))  # one per skill
    ctx.register_skill('make-reference', os.path.join(_HERE, "skills", 'make-reference', "SKILL.md"))  # one per skill
    ctx.register_skill('make-rubric', os.path.join(_HERE, "skills", 'make-rubric', "SKILL.md"))  # one per skill
    ctx.register_skill('make-vision-memo', os.path.join(_HERE, "skills", 'make-vision-memo', "SKILL.md"))  # one per skill
    ctx.register_skill('markdown-to-markup', os.path.join(_HERE, "skills", 'markdown-to-markup', "SKILL.md"))  # one per skill
    ctx.register_skill('product-lifecycle-rules', os.path.join(_HERE, "skills", 'product-lifecycle-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('project-facts', os.path.join(_HERE, "skills", 'project-facts', "SKILL.md"))  # one per skill
    ctx.register_skill('research-methods', os.path.join(_HERE, "skills", 'research-methods', "SKILL.md"))  # one per skill
    ctx.register_skill('research-rules', os.path.join(_HERE, "skills", 'research-rules', "SKILL.md"))  # one per skill
    ctx.register_skill('tidy-docs', os.path.join(_HERE, "skills", 'tidy-docs', "SKILL.md"))  # one per skill
