"""authorkit — generated by harness_emit.py from .claude-plugin/plugin.json. Do not edit."""
import os

_HERE = os.path.dirname(os.path.abspath(__file__))

def register(ctx):
    ctx.register_skill('attention-audit', os.path.join(_HERE, "skills", 'attention-audit', "SKILL.md"))  # one per skill
    ctx.register_skill('bloat-audit', os.path.join(_HERE, "skills", 'bloat-audit', "SKILL.md"))  # one per skill
    ctx.register_skill('doctrine-audit', os.path.join(_HERE, "skills", 'doctrine-audit', "SKILL.md"))  # one per skill
    ctx.register_skill('estate-audit', os.path.join(_HERE, "skills", 'estate-audit', "SKILL.md"))  # one per skill
    ctx.register_skill('exemption-retire', os.path.join(_HERE, "skills", 'exemption-retire', "SKILL.md"))  # one per skill
    ctx.register_skill('fix-old-names', os.path.join(_HERE, "skills", 'fix-old-names', "SKILL.md"))  # one per skill
    ctx.register_skill('host-audit', os.path.join(_HERE, "skills", 'host-audit', "SKILL.md"))  # one per skill
    ctx.register_skill('manifest-authoring', os.path.join(_HERE, "skills", 'manifest-authoring', "SKILL.md"))  # one per skill
    ctx.register_skill('naming-audit', os.path.join(_HERE, "skills", 'naming-audit', "SKILL.md"))  # one per skill
    ctx.register_skill('naming-conventions', os.path.join(_HERE, "skills", 'naming-conventions', "SKILL.md"))  # one per skill
    ctx.register_skill('orchestration-audit', os.path.join(_HERE, "skills", 'orchestration-audit', "SKILL.md"))  # one per skill
    ctx.register_skill('overhaul-execute', os.path.join(_HERE, "skills", 'overhaul-execute', "SKILL.md"))  # one per skill
    ctx.register_skill('overhaul-planning', os.path.join(_HERE, "skills", 'overhaul-planning', "SKILL.md"))  # one per skill
    ctx.register_skill('pattern-audit', os.path.join(_HERE, "skills", 'pattern-audit', "SKILL.md"))  # one per skill
    ctx.register_skill('recurrence-audit', os.path.join(_HERE, "skills", 'recurrence-audit', "SKILL.md"))  # one per skill
    ctx.register_skill('rename-execute', os.path.join(_HERE, "skills", 'rename-execute', "SKILL.md"))  # one per skill
    ctx.register_skill('rename-planning', os.path.join(_HERE, "skills", 'rename-planning', "SKILL.md"))  # one per skill
    ctx.register_skill('repo-audit', os.path.join(_HERE, "skills", 'repo-audit', "SKILL.md"))  # one per skill
    ctx.register_skill('spend-audit', os.path.join(_HERE, "skills", 'spend-audit', "SKILL.md"))  # one per skill
